// Pure Material Costs domain helpers (Phase 3, Portal).
//
// The data model is owned by the shared backend (Rork migration 247):
//   material_catalogue   — standard VineTrack items (id, key, name, category,
//                          default_unit, sort_order, is_active)
//   vineyard_materials   — per-vineyard overrides of a catalogue item
//                          (base_material_id) AND vineyard custom materials
//                          (is_custom, base_material_id null)
//   work_task_materials  — FROZEN per-task snapshot (material_name, category,
//                          unit, quantity, unit_cost, generated total_cost)
//
// Nothing here touches the network so the merge/dedupe/decimal rules can be
// tested directly. No Portal-specific material model is introduced.

/** A standard VineTrack catalogue item. */
export interface MaterialCatalogueItem {
  id: string;
  key?: string | null;
  name?: string | null;
  category?: string | null;
  default_unit?: string | null;
  sort_order?: number | null;
  is_active?: boolean | null;
}

/** A vineyard row: either an override of a catalogue item or a custom material. */
export interface VineyardMaterial {
  id: string;
  vineyard_id: string;
  /** Catalogue item this row overrides. Null for vineyard custom materials. */
  base_material_id?: string | null;
  name?: string | null;
  category?: string | null;
  unit?: string | null;
  default_unit_cost?: number | string | null;
  is_active?: boolean | null;
  is_custom?: boolean | null;
  deleted_at?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
}

/** One frozen material line on a work task. */
export interface WorkTaskMaterial {
  id: string;
  vineyard_id: string;
  work_task_id: string;
  /** Provenance only — display always uses the snapshot fields below. */
  vineyard_material_id?: string | null;
  material_name?: string | null;
  category?: string | null;
  unit?: string | null;
  quantity?: number | string | null;
  unit_cost?: number | string | null;
  /** Generated by the backend: quantity * unit_cost. */
  total_cost?: number | string | null;
  notes?: string | null;
  deleted_at?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
  sync_version?: number | null;
}

/**
 * One logical row in the Add Material selector and the Material Library: the
 * effective vineyard version of a material. A standard catalogue item and its
 * vineyard override are ALWAYS one row, never two.
 */
export interface EffectiveMaterial {
  /** Stable selector identity. */
  key: string;
  /** Catalogue item id, when this row comes from the standard catalogue. */
  catalogueId: string | null;
  /** vineyard_materials.id, when a vineyard row exists (override or custom). */
  vineyardMaterialId: string | null;
  name: string;
  category: string;
  /** Effective unit: vineyard override wins over catalogue default_unit. */
  unit: string;
  /** Effective default price as a decimal string; null when never priced. */
  defaultUnitCost: string | null;
  isCustom: boolean;
  /** True when a vineyard override/custom row exists and is active. */
  isActive: boolean;
  /** True when a vineyard row overrides the standard catalogue item. */
  hasVineyardOverride: boolean;
}

export const OTHER_CATEGORY = "Other";

/** Display order for the high-level Material Costs categories (migration 247). */
export const MATERIAL_CATEGORY_ORDER: string[] = [
  "Trellis",
  "Fasteners & Training",
  "Netting & Protection",
  "Irrigation",
  "Vine Establishment",
  OTHER_CATEGORY,
];

/** Standard unit suggestions; free-text units from the backend still work. */
export const MATERIAL_UNIT_SUGGESTIONS = ["Each", "Metre", "Roll", "Pack", "Box", "Bag"];

const text = (v: unknown): string => (v == null ? "" : String(v).trim());

/**
 * Options for the Unit dropdown: the six shared iOS/Android/Portal choices.
 * Unit is stored as text and historical records may hold a value outside the
 * standard list, so the record's current unit is appended when non-standard —
 * editing it must never silently change or lose the stored value.
 */
export function materialUnitOptions(currentUnit: string | null | undefined): string[] {
  const current = text(currentUnit);
  if (!current || MATERIAL_UNIT_SUGGESTIONS.includes(current)) {
    return [...MATERIAL_UNIT_SUGGESTIONS];
  }
  return [...MATERIAL_UNIT_SUGGESTIONS, current];
}

export function materialCategoryRank(category: string): number {
  const i = MATERIAL_CATEGORY_ORDER.indexOf(category);
  return i === -1 ? MATERIAL_CATEGORY_ORDER.length : i;
}

// ------------------------- decimal-safe numerics -------------------------
//
// quantity / unit_cost / total are PostgreSQL numeric. Authoritative values are
// carried as decimal strings and multiplied with integer maths, so no financial
// value is reconstructed through binary floating point.

interface Scaled {
  /** Signed integer mantissa. */
  units: bigint;
  /** Number of decimal places. */
  scale: number;
}

function parseDecimal(value: unknown): Scaled | null {
  if (value == null) return null;
  const raw = String(value).trim();
  if (raw === "") return null;
  if (!/^[-+]?(\d+(\.\d*)?|\.\d+)$/.test(raw)) return null;
  const negative = raw.startsWith("-");
  const body = raw.replace(/^[-+]/, "");
  const [intPart, fracPart = ""] = body.split(".");
  const digits = `${intPart || "0"}${fracPart}`;
  const units = BigInt(digits === "" ? "0" : digits);
  return { units: negative ? -units : units, scale: fracPart.length };
}

function scaledToString(v: Scaled): string {
  const negative = v.units < 0n;
  let digits = (negative ? -v.units : v.units).toString();
  if (v.scale === 0) return `${negative ? "-" : ""}${digits}`;
  digits = digits.padStart(v.scale + 1, "0");
  const intPart = digits.slice(0, digits.length - v.scale);
  const frac = digits.slice(digits.length - v.scale).replace(/0+$/, "");
  return `${negative ? "-" : ""}${intPart}${frac ? `.${frac}` : ""}`;
}

/** Rounds a scaled value to `dp` decimals, half-up on the absolute value. */
function roundScaled(v: Scaled, dp: number): Scaled {
  if (v.scale <= dp) {
    const factor = 10n ** BigInt(dp - v.scale);
    return { units: v.units * factor, scale: dp };
  }
  const drop = 10n ** BigInt(v.scale - dp);
  const negative = v.units < 0n;
  const abs = negative ? -v.units : v.units;
  const q = abs / drop;
  const rem = abs % drop;
  const rounded = rem * 2n >= drop ? q + 1n : q;
  return { units: negative ? -rounded : rounded, scale: dp };
}

/** Normalises a user-entered decimal to a canonical string, or null. */
export function normaliseDecimalInput(value: unknown): string | null {
  const parsed = parseDecimal(value);
  return parsed ? scaledToString(parsed) : null;
}

export function isPositiveDecimal(value: unknown): boolean {
  const parsed = parseDecimal(value);
  return !!parsed && parsed.units > 0n;
}

export function decimalToNumber(value: unknown): number | null {
  const s = normaliseDecimalInput(value);
  if (s == null) return null;
  const n = Number(s);
  return Number.isFinite(n) ? n : null;
}

/**
 * quantity × unit cost, rounded to 2 decimals with integer maths. Returns a
 * decimal string, or null when either side is missing/unparseable. Mirrors the
 * backend's generated total_cost so the live editor total matches what is saved.
 */
export function multiplyDecimals(quantity: unknown, unitCost: unknown, dp = 2): string | null {
  const q = parseDecimal(quantity);
  const c = parseDecimal(unitCost);
  if (!q || !c) return null;
  const product: Scaled = { units: q.units * c.units, scale: q.scale + c.scale };
  return scaledToString(roundScaled(product, dp));
}

/** Sums decimal strings/numbers with integer maths. Returns a decimal string. */
export function sumDecimals(values: ReadonlyArray<unknown>, dp = 2): string {
  let total = 0n;
  for (const v of values) {
    const parsed = parseDecimal(v);
    if (!parsed) continue;
    total += roundScaled(parsed, dp).units;
  }
  return scaledToString({ units: total, scale: dp });
}

/**
 * Material Total for a task: the sum of ACTIVE (non-deleted) line totals,
 * preferring the backend-generated total_cost and falling back to
 * quantity × unit_cost for rows saved before the generated value is read back.
 */
export function materialTotalForTask(lines: ReadonlyArray<WorkTaskMaterial>): string {
  const active = lines.filter((l) => !l.deleted_at);
  return sumDecimals(
    active.map((l) =>
      l.total_cost != null && String(l.total_cost).trim() !== ""
        ? l.total_cost
        : multiplyDecimals(l.quantity, l.unit_cost),
    ),
  );
}

/** Numeric Material Total, for combining with existing cost roll-ups. */
export function materialTotalNumber(lines: ReadonlyArray<WorkTaskMaterial>): number {
  return decimalToNumber(materialTotalForTask(lines)) ?? 0;
}

export function groupWorkTaskMaterialsByTask(
  lines: ReadonlyArray<WorkTaskMaterial>,
): Map<string, WorkTaskMaterial[]> {
  const map = new Map<string, WorkTaskMaterial[]>();
  lines.forEach((line) => {
    if (line.deleted_at) return;
    const list = map.get(line.work_task_id) ?? [];
    list.push(line);
    map.set(line.work_task_id, list);
  });
  return map;
}

// ------------------------- merged material library -------------------------

/**
 * Merges the standard catalogue with this vineyard's rows into ONE logical row
 * per material:
 *   - standard catalogue identity is kept
 *   - a vineyard override supplies the effective unit / default price
 *   - active vineyard custom materials are appended
 * A catalogue item and its override are never returned twice.
 */
export function mergeEffectiveMaterials(
  catalogue: ReadonlyArray<MaterialCatalogueItem>,
  vineyardMaterials: ReadonlyArray<VineyardMaterial>,
): EffectiveMaterial[] {
  const live = vineyardMaterials.filter((v) => !v.deleted_at);
  const overrideByBase = new Map<string, VineyardMaterial>();
  live.forEach((v) => {
    if (v.base_material_id) overrideByBase.set(v.base_material_id, v);
  });

  const standard: EffectiveMaterial[] = catalogue
    .filter((c) => c.is_active !== false)
    .map((c) => {
      const override = overrideByBase.get(c.id) ?? null;
      const category = text(override?.category) || text(c.category) || OTHER_CATEGORY;
      return {
        key: `catalogue:${c.id}`,
        catalogueId: c.id,
        vineyardMaterialId: override?.id ?? null,
        name: text(c.name) || text(override?.name) || "Material",
        category,
        unit: text(override?.unit) || text(c.default_unit) || "Each",
        defaultUnitCost: normaliseDecimalInput(override?.default_unit_cost ?? null),
        isCustom: false,
        // Standard items are always selectable; a vineyard cannot delete them.
        isActive: true,
        hasVineyardOverride: !!override,
      } satisfies EffectiveMaterial;
    })
    .sort(
      (a, b) =>
        byCatalogueOrder(catalogue, a.catalogueId, b.catalogueId) || a.name.localeCompare(b.name),
    );

  const custom: EffectiveMaterial[] = live
    .filter((v) => !v.base_material_id)
    .map((v) => ({
      key: `vineyard:${v.id}`,
      catalogueId: null,
      vineyardMaterialId: v.id,
      name: text(v.name) || "Custom material",
      category: text(v.category) || OTHER_CATEGORY,
      unit: text(v.unit) || "Each",
      defaultUnitCost: normaliseDecimalInput(v.default_unit_cost ?? null),
      isCustom: true,
      isActive: v.is_active !== false,
      hasVineyardOverride: true,
    }))
    .sort((a, b) => a.name.localeCompare(b.name));

  return [...standard, ...custom];
}

function byCatalogueOrder(
  catalogue: ReadonlyArray<MaterialCatalogueItem>,
  a: string | null,
  b: string | null,
): number {
  const order = (id: string | null) => {
    const item = catalogue.find((c) => c.id === id);
    return item?.sort_order ?? Number.MAX_SAFE_INTEGER;
  };
  return order(a) - order(b);
}

/** Selection list: active rows only (deactivated custom materials drop out). */
export function selectableMaterials(
  materials: ReadonlyArray<EffectiveMaterial>,
): EffectiveMaterial[] {
  return materials.filter((m) => m.isActive);
}

export function searchMaterials(
  materials: ReadonlyArray<EffectiveMaterial>,
  term: string,
): EffectiveMaterial[] {
  const q = text(term).toLowerCase();
  if (!q) return [...materials];
  return materials.filter(
    (m) => m.name.toLowerCase().includes(q) || m.category.toLowerCase().includes(q),
  );
}

export interface MaterialCategoryGroup {
  category: string;
  materials: EffectiveMaterial[];
}

/** Groups selector/library rows by the existing high-level categories. */
export function groupMaterialsByCategory(
  materials: ReadonlyArray<EffectiveMaterial>,
): MaterialCategoryGroup[] {
  const groups = new Map<string, EffectiveMaterial[]>();
  materials.forEach((m) => {
    const list = groups.get(m.category) ?? [];
    list.push(m);
    groups.set(m.category, list);
  });
  return Array.from(groups.entries())
    .map(([category, list]) => ({ category, materials: list }))
    .sort(
      (a, b) =>
        materialCategoryRank(a.category) - materialCategoryRank(b.category) ||
        a.category.localeCompare(b.category),
    );
}

/** Categories offered when creating/editing a vineyard custom material. */
export function customMaterialCategories(
  catalogue: ReadonlyArray<MaterialCatalogueItem>,
): string[] {
  const set = new Set<string>(MATERIAL_CATEGORY_ORDER);
  catalogue.forEach((c) => {
    const category = text(c.category);
    if (category) set.add(category);
  });
  return Array.from(set).sort(
    (a, b) => materialCategoryRank(a) - materialCategoryRank(b) || a.localeCompare(b),
  );
}

/** Compact display line, e.g. "12 Each × $1.82". */
export function materialLineSummary(
  line: Pick<WorkTaskMaterial, "quantity" | "unit" | "unit_cost">,
  formatMoney: (n: number) => string,
): string {
  const qty = normaliseDecimalInput(line.quantity) ?? "0";
  const unit = text(line.unit);
  const cost = decimalToNumber(line.unit_cost);
  const left = unit ? `${qty} ${unit}` : qty;
  return cost == null ? left : `${left} × ${formatMoney(cost)}`;
}
