/* eslint-disable @typescript-eslint/no-explicit-any -- test double for the Supabase query builder */
import { describe, it, expect, vi, beforeEach } from "vitest";

interface Call {
  table: string;
  op: "select" | "insert" | "update";
  payload: any;
  filters: [string, unknown][];
  isNull: string[];
}

const state: {
  calls: Call[];
  result: { data: any; error: any };
} = { calls: [], result: { data: { id: "row-1" }, error: null } };

function builder(table: string) {
  const call: Call = { table, op: "select", payload: null, filters: [], isNull: [] };
  state.calls.push(call);
  const api: any = {
    select: (cols?: string) => {
      if (call.op === "select") call.payload = cols ?? "*";
      return api;
    },
    insert: (payload: any) => {
      call.op = "insert";
      call.payload = payload;
      return api;
    },
    update: (payload: any) => {
      call.op = "update";
      call.payload = payload;
      return api;
    },
    eq: (col: string, val: unknown) => {
      call.filters.push([col, val]);
      return api;
    },
    is: (col: string) => {
      call.isNull.push(col);
      return api;
    },
    order: () => api,
    single: () => Promise.resolve(state.result),
    then: (resolve: any, reject: any) => Promise.resolve(state.result).then(resolve, reject),
  };
  return api;
}

vi.mock("@/integrations/ios-supabase/client", () => ({
  supabase: { from: (table: string) => builder(table) },
}));

import {
  addWorkTaskMaterial,
  describeMaterialError,
  fetchVineyardMaterials,
  fetchWorkTaskMaterials,
  removeWorkTaskMaterial,
  saveCustomMaterial,
  saveVineyardMaterialOverride,
  setCustomMaterialActive,
  updateWorkTaskMaterial,
} from "@/lib/materialsQuery";

beforeEach(() => {
  state.calls = [];
  state.result = { data: { id: "row-1" }, error: null };
});

const last = () => state.calls[state.calls.length - 1];

describe("work task material writes", () => {
  it("adds one frozen snapshot line and lets the backend generate the total", async () => {
    await addWorkTaskMaterial({
      vineyardId: "v1",
      workTaskId: "t1",
      vineyardMaterialId: "vm-1",
      materialName: "Gripple / Wire Joiner-Tensioner",
      category: "Fasteners & Training",
      unit: "Each",
      quantity: "12",
      unitCost: "1.82",
      userId: "u1",
    });
    const call = last();
    expect(call.table).toBe("work_task_materials");
    expect(call.op).toBe("insert");
    expect(call.payload).toMatchObject({
      vineyard_id: "v1",
      work_task_id: "t1",
      vineyard_material_id: "vm-1",
      material_name: "Gripple / Wire Joiner-Tensioner",
      category: "Fasteners & Training",
      unit: "Each",
      quantity: "12",
      unit_cost: "1.82",
    });
    // total_cost is generated by the backend and never sent.
    expect(Object.keys(call.payload)).not.toContain("total_cost");
  });

  it("edits the existing line instead of inserting a second row", async () => {
    await updateWorkTaskMaterial({
      vineyardId: "v1",
      id: "line-1",
      unit: "Each",
      quantity: "14",
      unitCost: "2.00",
    });
    const call = last();
    expect(call.op).toBe("update");
    expect(call.filters).toContainEqual(["id", "line-1"]);
    expect(call.filters).toContainEqual(["vineyard_id", "v1"]);
    expect(call.isNull).toContain("deleted_at");
    expect(state.calls.filter((c) => c.op === "insert")).toHaveLength(0);
  });

  it("does not push a task-specific cost back into the Material Library", async () => {
    await updateWorkTaskMaterial({
      vineyardId: "v1",
      id: "line-1",
      unit: "Each",
      quantity: "14",
      unitCost: "9.99",
    });
    expect(state.calls.some((c) => c.table === "vineyard_materials")).toBe(false);
  });

  it("removes only the task line via soft delete", async () => {
    await removeWorkTaskMaterial("v1", "line-1", "u1");
    const call = last();
    expect(call.table).toBe("work_task_materials");
    expect(call.op).toBe("update");
    expect(call.payload.deleted_at).toBeTruthy();
    expect(call.filters).toContainEqual(["vineyard_id", "v1"]);
    expect(state.calls.some((c) => c.table === "material_catalogue")).toBe(false);
    expect(state.calls.some((c) => c.table === "vineyard_materials")).toBe(false);
  });

  it("never reports success when the backend write fails", async () => {
    state.result = { data: null, error: { code: "42501", message: "permission denied" } };
    await expect(
      addWorkTaskMaterial({
        vineyardId: "v1",
        workTaskId: "t1",
        vineyardMaterialId: null,
        materialName: "Gripple / Wire Joiner-Tensioner",
        category: "Fasteners & Training",
        unit: "Each",
        quantity: "1",
        unitCost: "1",
      }),
    ).rejects.toMatchObject({ code: "42501" });
  });
});

describe("vineyard material library writes", () => {
  it("creates a vineyard override without duplicating the catalogue row", async () => {
    await saveVineyardMaterialOverride({
      vineyardId: "v1",
      baseMaterialId: "cat-grip",
      name: "Gripple / Wire Joiner-Tensioner",
      category: "Fasteners & Training",
      unit: "Each",
      defaultUnitCost: "1.82",
      vineyardMaterialId: null,
    });
    const call = last();
    expect(call.table).toBe("vineyard_materials");
    expect(call.op).toBe("insert");
    expect(call.payload).toMatchObject({
      vineyard_id: "v1",
      base_material_id: "cat-grip",
      is_custom: false,
      default_unit_cost: "1.82",
    });
    expect(state.calls.some((c) => c.table === "material_catalogue")).toBe(false);
  });

  it("updates an existing override in place, scoped to the vineyard", async () => {
    await saveVineyardMaterialOverride({
      vineyardId: "v1",
      baseMaterialId: "cat-grip",
      name: "Gripple / Wire Joiner-Tensioner",
      category: "Fasteners & Training",
      unit: "Pack",
      defaultUnitCost: "2.50",
      vineyardMaterialId: "vm-1",
    });
    const call = last();
    expect(call.op).toBe("update");
    expect(call.filters).toContainEqual(["id", "vm-1"]);
    expect(call.filters).toContainEqual(["vineyard_id", "v1"]);
  });

  it("creates a custom material owned by the selected vineyard only", async () => {
    await saveCustomMaterial({
      vineyardId: "v1",
      name: "Estate Vine Guard",
      category: "Vine Establishment",
      unit: "Each",
      defaultUnitCost: "0.75",
    });
    const call = last();
    expect(call.payload).toMatchObject({
      vineyard_id: "v1",
      is_custom: true,
      base_material_id: null,
      name: "Estate Vine Guard",
    });
  });

  it("deactivates and reactivates a custom material without deleting it", async () => {
    await setCustomMaterialActive("v1", "vm-a", false);
    expect(last().payload).toMatchObject({ is_active: false });
    expect(Object.keys(last().payload)).not.toContain("deleted_at");
    await setCustomMaterialActive("v1", "vm-a", true);
    expect(last().payload).toMatchObject({ is_active: true });
  });
});

describe("vineyard scoping and error messages", () => {
  it("scopes every read to the selected vineyard and excludes deleted rows", async () => {
    state.result = { data: [], error: null };
    await fetchVineyardMaterials("v1");
    expect(last().filters).toContainEqual(["vineyard_id", "v1"]);
    expect(last().isNull).toContain("deleted_at");
    await fetchWorkTaskMaterials("v2");
    expect(last().filters).toContainEqual(["vineyard_id", "v2"]);
    expect(last().isNull).toContain("deleted_at");
  });

  it("explains failures without leaking backend error text", () => {
    expect(describeMaterialError({ code: "42501" }, "fallback")).toMatch(/no longer have access/i);
    expect(describeMaterialError({ code: "PGRST116" }, "fallback")).toMatch(/already been changed/i);
    expect(describeMaterialError({ code: "42P01" }, "fallback")).toMatch(/not available/i);
    expect(describeMaterialError({ message: "boom" }, "fallback")).toBe("fallback");
  });
});
