import { Card } from "@/components/ui/card";
import { FolderOpen, Info } from "lucide-react";

export default function DocumentsPage() {
  return (
    <div className="p-6 space-y-6 max-w-4xl">
      <div>
        <h1 className="text-2xl font-semibold">iOS Documents</h1>
        <p className="text-sm text-muted-foreground mt-1">
          Library of PDF, CSV and Excel files exported from the iOS app.
        </p>
      </div>

      <Card className="p-6 space-y-3 text-center">
        <FolderOpen className="h-8 w-8 mx-auto text-muted-foreground" />
        <div className="font-medium">Document library not connected</div>
        <p className="text-sm text-muted-foreground max-w-xl mx-auto">
          This area will list exports generated by the iOS app once a document
          index or storage bucket is available. No storage buckets or document
          metadata tables are currently configured for this vineyard.
        </p>
      </Card>

      <Card className="p-4 space-y-2 bg-muted/30">
        <div className="flex items-center gap-2 font-medium text-sm">
          <Info className="h-4 w-4" /> What is needed
        </div>
        <ul className="text-xs text-muted-foreground space-y-1 list-disc pl-5">
          <li>
            A Supabase storage bucket (e.g.{" "}
            <code className="font-mono">vineyard-documents</code>) with RLS
            scoping uploads to the owning vineyard, or
          </li>
          <li>
            A <code className="font-mono">documents</code> metadata table linking
            files to vineyard, type, author and created_at, populated by the iOS
            app on export.
          </li>
          <li>
            Once either exists, this page will list, filter and download files
            read-only; the portal will not generate iOS exports itself.
          </li>
        </ul>
      </Card>
    </div>
  );
}
